### ISSUE TITLE
composer.json is incorrect

### ISSUE THREAD

**Issue by andreaskou** [Aurelienazerty/darkMode#3]
`name": "aurelienazerty/darkmode",`
Should be
`name": "Aurelienazerty/darkMode",`

Though ffter correcting this, my extensions page in ACP goes white.
PHPBB ver 3.3.0

All the best!

**Comment by Aurelienazerty** [comment]
No, Camel case is not allowed anymore : https://area51.phpbb.com/docs/dev/3.3.x/extensions/tutorial_basics.html#introduction
